mango-gremlin/arch-enemies

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/new-feature.md, .github/ISSUE_TEMPLATE/tasklist.md
To make creating issues easier & standardised, here are some issue templates. Feel free to add if we need any more.
Pull Request Templates coming soon
Please add your thoughts below & approve if you think they're okay.
=> Add issue templates

docs/meeting_notes/general_meetings/23-11-16_Prototype-Plan.md
Added Prototype Plan Notes for the bridge prototype.
=> Added prototype plan notes from meeting at 23-11-16

.gitignore
Created a gitignore for godot files with the godot gitignore template.
added gitignore clauses for things we dont want to push with each commit.
I propose we try this out and then maybe add/remove things as we go, is everyone okay with this?
=> Created .gitignore for godot files

testing_area/prototype_testing/README.md
To track prototypes in an organised way.
Added folders testing_area/prototype_testing, name conventions for prototype names are in the readme.
=> Added prototype testing file structure

testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/DragObject.gd
closes #35
added a check if something is being dragged allready and if that thing is self
works 
https://github.com/mango-gremlin/arch-enemies/assets/44133213/45ad7e83-b973-4c0c-a637-c1554d0717f5
the Branch is named issue27/... by mistake
=> only one thing is draggable at a time, so animals dont stick

.github/pull_request_template.md
the keyword "closes issue ..." doesnt automatically connect the PR with the respective issue
-> the keyword "closes #xxx" automatically connects the issue with the PR so the issue will be closed if the PR is merged or closed.
=> updated pr template so closing keywords work now

docs/meeting_notes/general_meetings/meeting_cour_20231130.md
Added meeting notes from **high court meeting** on 2023-11-30 from 1000 to 1130.
=> add meeting notes, high court 20231130

testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/DragObject.gd, testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/global.gd, testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/world.tscn
closes #64
added drop zones to the Shore with new Group "shore_dropzone"
https://github.com/mango-gremlin/arch-enemies/assets/44133213/ef36e82a-defa-454e-a7d5-ffd333f1b86f
=> added drop zones to shore

testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/SnakeSpawningButton.gd, testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/SquirrelSpawning.gd, testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/SquirrelSpawningButton.gd, testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/world.tscn
closes #82 
The game is now technically solvable for presentation purposes.
These changes also demonstrate how we can go about implementing the spawning of animals.
I added buttons to spawn snakes and squirrels. Each is connected to a script that preloads the respective animal and instantiates a copy of it at the 100/100 coordinates upon pressing the button.
Summoning new animals:
https://github.com/mango-gremlin/arch-enemies/assets/116198748/0fdb6508-bc76-4302-bceb-0f54b7fe9fb4
Winning with a big bridge of snakes:
https://github.com/mango-gremlin/arch-enemies/assets/116198748/4ea2a877-03f2-4dde-8d6d-a3077d837c61
=> Made Level Solvable

Arch-enemies/overworld/entities/Player/Player.gd, Arch-enemies/overworld/scripts/Item.gd, Arch-enemies/overworld/scripts/save_management.gd, Arch-enemies/overworld/ui/overworld_ui/overworld_ui.gd
closes #139
Works. The only thing is, that the honey can only added once (and again after rejoining overworld). I don't belive that this has something to do with my implementation. Because with the stick it works perfectly.
Inventory is not shown on joining overworld. This issue has already been resolved. See https://github.com/mango-gremlin/arch-enemies/pull/141
=> changed inventory system #139

Arch-enemies/bridges/scenes/bridge_1.tscn, Arch-enemies/bridges/scenes/goal_menu.tscn, Arch-enemies/bridges/script/goal_menu.gd, Arch-enemies/bridges/script/player.gd
closes #159 
GoalMenu does have a clunky implementation and the naming doesn't adhere to the style guide.
Deleted some unnecassary nodes and skript and changed name to "goal_menu" to adhere to style guide.
The code still worked as expected.
=> refactored goal_menu

Arch-enemies/bridges/scenes/bridge_1.tscn, Arch-enemies/shore.tscn
closes #161
Put the Shore in a seperate scene
=> Put the Shore in a seperate scene

Arch-enemies/bridges/scenes/Grid.tscn, Arch-enemies/bridges/script/DRAGPREVIEW.gd, Arch-enemies/bridges/script/grid.gd, Arch-enemies/bridges/script/grid_drag.gd
closes #207 
Squirrel was missing from new grid approach, so it needed to be re-added.
Squirrel can cling to SIDE zones, so #199 had to be implemented first.
Added squirrel related code in all places where other animals where implemented.
=> Added squirrel again to new grid approach

README.md
Add the author/licensing for the font to the readme.
No other changes have been made.
=> Add font licensing to readme

Arch-enemies/bridges/script/player.gd
closes #284
https://github.com/mango-gremlin/arch-enemies/assets/44133213/e291f79a-7078-479c-98af-d0b26bc3befb
=> the fox animation changes now to idle when switching to drag mode

Arch-enemies/overworld/entities/interaction_overworld/bridge_interaction_animation.gd, Arch-enemies/overworld/entities/interaction_overworld/template/horizontal_bridge_template.tscn, Arch-enemies/overworld/entities/interaction_overworld/template/vertical_bridge_template.tscn
=> overworld | added interaction indicator to bridges

Arch-enemies/assets/art/characters/portraits/portrait_snake.png.import
The export file currently up to date was added, and the snake portrait file was changed. Everything should work for the playtest.
yay
=> Added the export file

Arch-enemies/bridges/script/goal.gd, Arch-enemies/bridges/script/grid.gd
closes #323 
Code is "solid", tested it locally.
=> Bridges: Walking sound continues after reaching goal area

Arch-enemies/overworld/entities/Player/Player.gd
=> Fixes sound and animation issue when opening a dialogue

README.md
Trailer would be nice
Added trailer to readme
=> added trailer to readme
