mango-gremlin/arch-enemies

- README.md
Make people aware we have a wiki. Use the wiki.
I added a link to the wiki to the readme - ALSO: What exactly are we going to put in the readme? 
**Proposals:**
1. Game Design Finalised Ideas that will serve as guide to implementation (so we have everything in one place)
2. How we want to implement things / guide & documentation to implementation? (or should that stay in the docs?)
3. What else?
Please let me know what you think, multiple things can also work. I think 1 and 2 would both be very helpful, maybe we can split the wiki up a little bit?
---
- a banner with the arch-enemy front image ( acting as opening for the github-page)
- short context ( who we are, what we work on )
- Overview of game ( short summary of what this game is about, maybe 3-4 sentences at most? )
- some …
> Edited README.md to include wiki info, game info, license 

- docs/meeting_notes/general_meetings/23-11-19_first_sprint.md
>**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
I'll be violating this rule now, Excuse me. 
Keeping this repo up to date by maintaining and uploading notes gathered from meetings. 
Specifically this PR adds notes taken on 2023-11-19.
Added 23-11-19_first_sprint.md to the documentation located at `/docs/meeting_notes/general_meetings/*`
> add meeting notes from 20231119

- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/DragObject.gd
- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/ModeChangeButton.gd
- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/allowed_snake_area.gd
- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/fox.gd
- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/snek.tscn
closes issue #30
The snake has now dropzones on all sides, excluding the head. The code was also refactored to make adding more dropzones as simple as possible.
Added dropzones (StaticBody2D with CollisionBody2D and ColorRect) manually, connected it with the allowed_snake_area script and added the neccessary "dropable" and "left/top/bottom_dropzone" groups for identification.
In DragObject.gd, all variables for the left dropzone were changed to general dropzone variables and the function "calculate_dropzones" was added to calculate the new snapping position depending on the dropzone.
I also fixed all those annoying warnings (mainly unused parameters in functions).
https://github.com/mango-gremlin/arch-enemies/assets/57258671/e8416f63-ad1c-4e09-9e98-7c40b8b224fd
While it does work, hitting …
> add general dropzones on all sides of the snake

- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/DragObject.gd
- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/world.tscn
closes #32 
Dragged snake now snaps to nearest position within grid after releasing the click button, before considering if it is within a placeable zone or not. Currently a grid square size of 10x10 pixels is assumed, this can be changed via the ``grid_size`` variable. Getting the nearest grid square is done using the ``round_to_nearest(a:float, b:float)`` function. 
Also, initial placements of snakes has been adjusted to the 10x10 grid.
The effect is barely noticable, as it occurs in the same frame as the snapping to droppable/return to original position. Using print statements, however, confirms the functionality of the code (not included in commit, but printing ``self.position`` before and after the snap can be tested).
Adds the helper function ``round_to_nearest(a:float, b:float)``, …
> added grid snap functionality after releasing snake

- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/DragObject.gd
- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/project.godot
closes #28 
Previously it was possible to drag the snakes while in fox mode. We want the player to switch between the bridge building and the bridge crossing, so that had to change.
I added a condition requiring drag mode to be true to the dragging function and the mouse-over highlight function.
I tested the change in the Godot debug mode:
https://github.com/mango-gremlin/arch-enemies/assets/116198748/c092cb91-852b-49a5-bee3-49d3728003d8
The changes are built onto the base project Prototype_Bridges_1.3
> Disabled dragging in fox mode

- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/DragObject.gd
closes #67
When picking up the object (e.g. a snake) it might be displayed behind other objects. To make the currently dragged object more visible and stand out more it should always be displayed on top of everything else.
In DragObject.gd the top_level of the dragged object will be set to true if the action is just pressed and it will be set to false if the action is just released.
https://github.com/mango-gremlin/arch-enemies/assets/116217918/44772f8c-ab2a-4366-bff7-158e2c134668
> Fixed: dragged object should be on top level

- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/project.godot
- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/snek.tscn
- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/squirrel.tscn
- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/world.tscn
closes #49
The Dropbox collision bug was a major bug prohibiting proper jump/run 
To fix the Bug all the dropboxes are now on Physics layer two. The main snake collision box now is on both Physics layer one and two. 
In the main document the Physics layer one and two have been renamed to showcases their purpose.
The behavior and drag and drop feels very janky. It behaves the same as before as far as I can tell and test, but I cannot guarantee that the behavior hasn't changed in some edge cases.
Resolves https://github.com/mango-gremlin/arch-enemies/issues/49
> Fixed Dropbox collision bug

- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/DragObject.gd
- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/squirrel.tscn
- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/world.tscn
closes #77 
Squirrel was moved 5 pixel downwards, hitboxes have been adjusted accordingly. This fixed the grid-snapping, but allowed placement of the squirrel wherever you wanted, because it detected its own hitboxes as valid dropzones. To fix this, we changed the ``is_correct_placement`` function so that it ignores its own valid dropzones.
As you can see, the squirrel snaps to grid, and correctly snaps back if placed in a forbidden spot.
https://github.com/mango-gremlin/arch-enemies/assets/104799849/cfd5d6d5-f491-4797-a62f-26441c1ee590
> Squirrel now snaps to grid correctly

- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/SpiderSpawningButton.gd
- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/world.tscn
closes #102 
We added spiders to the game, so we need a button to spawn them so they can be used to build the bridge.
I added a button that is connected to a script that instantiates a spider when the button is pressed.
I also changed the size and position of the button, because we want to make the level smaller and sorted all of the control element nodes to be next to each other in the scene tree.
Conjuring a spider:
https://github.com/mango-gremlin/arch-enemies/assets/116198748/6df52cf2-a9ac-46eb-8003-2818861bfb02
> Added a button that spawns spiders.

- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/snek.tscn
closes #104 
Slightly adjusted snake hitboxes so they (visually) fit the grid. Took most of the work from #86, adjusted it only slighty 
As seen below, the snake and its hitboxes fits the grid 
https://github.com/mango-gremlin/arch-enemies/assets/104799849/2a0208a8-58cd-4027-928b-bbb3626108b6
As you can see below, the hitboxes still don't look pretty internall, especially considering the centering of the collision zones. After the prototypes have been merged together, we might want to fix that. 
Also, the red rectangle is now brown thanks to the background, it doesn't look good.
> adjusted snake hitboxes to fit grid

- testing_area/prototype_testing/MarcelRaffaelKatjaGlenn_BridgeNoGridPrototype1/Prototype_Bridges_1.3/DragObject.gd
closes #112 
added one line of code that checks if animal was in forbidden zone before considering animal-specific/shore-specific placement
[Screencast from 04.12.2023 13:59:01.webm](https://github.com/mango-gremlin/arch-enemies/assets/104799849/8032d3cb-fcc5-4c01-8632-ec0a95283ef0)
Found another bug: if you drag an animal through two overlapping forbidden zones, then ``is_inside_forbidden`` is always ``true``.  Should be fixed in #87, as overlapping forbidden zones should not longer be possible in general (maybe except hazards?)
> fix spider adjacent placement

- Arch-enemies/bridges/scenes/animals/snake.tscn
- Arch-enemies/bridges/scenes/animals/spider.tscn
- Arch-enemies/bridges/scenes/animals/squirrel.tscn
- Arch-enemies/bridges/scenes/bridge_1.tscn
closes #129
When attaching animals to each other the correct zones should light up.
On the squirrel and spider the collision zones of the top and right dropzone where switched, so I switched them to their correct position. Additionally collision zones register overlap even if they only occupy adjacent pixels and their edges touch, so I reduced the size of the collision zones by 1 around the edges. This should not lead to any problems since animals only move in increments of 10
https://github.com/mango-gremlin/arch-enemies/assets/116198748/1b95f440-119b-4611-adb7-462d77e2986e
> Fixed wrong dropzones lighting up

- Arch-enemies/bridges/scenes/bridge_1.tscn
- Arch-enemies/bridges/scenes/world_edge.tscn
closes #131 
Before now, the player could walk off the edges of our level and fall infinitely. While resetting the position by changing into drag mode is possible, it should be prevented from the start.
I added simple collision boxes called "world_edge_left" and "world_edge_right"
https://github.com/mango-gremlin/arch-enemies/assets/57258671/5683453b-a2b3-4d0a-8039-cdb853e8ac6b
Please ignore the... unusual bridge.
But the collision boxes work.
I had to make the goal hitbox a bit smaller, or my collision shape would trigger it.
> Add world edge collision boxes

- Arch-enemies/bridges/script/grid.gd
- Arch-enemies/bridges/script/grid_drag.gd
closes #199
Before adding the squirrel and its ability it is necessary to differentiate between a side-conditional and a bottom-conditional.
In `grid.gd` and `grid_drag.gd` the ENTITY_TYPES.CONDITIONAL has been split up into SIDE and BOTTOM and assigned accordingly in each instance.
The bridge building works just like before, the real difference will be visible when the squirrel is implemented.
Right now SIDE and BOTTOM zones have the same color, but we could change that if desired.
> Separated CONDITIONAL into SIDE and BOTTOM

- Arch-enemies/overworld/entities/interaction_overworld/npc_interaction.gd
- Arch-enemies/overworld/entities/interaction_overworld/npc_interaction.tscn
- Arch-enemies/overworld/main_scene_overworld.tscn
resolves #224 
~~**requires** #232 !~~ was incorporated already, sorry!
Adds a method that runs upon **initialization** of a npc_interaction ( so the interactionspot within the overworld that denotes the npc interaction ) and then **loads/sets** the corresponding sprite for displaying said animal. 
Furthermore a new **exported variable** was defined that can be set to be **an invariante**, so  a special texture for a given npc. 
The method considers this invariant and prioritizes it over the default animal-sprites.
The overworld now contains all the npc interactions with their corresponding sprites ( **not the final ones however** ):
Furthermore in the lower corner an invariant was added ( Esther is a failed square now):
> overworld | autoloading sprites for npcs

- Arch-enemies/overworld/scripts/Npc.gd
- Arch-enemies/overworld/ui/overworld_ui/overworld_ui.gd
- Arch-enemies/singleton_scripts/singleton_player.gd
This pr aims to add a functionality to **visually** track Quests occurring in the overworld. 
Its done by adding a new dictionary within the singleton which will track / contain each quest as string ( linked to its npc_id ) 
resolves #191 
resolves #189 
-  added **Dictionary** `quest_string_dict` in singleton_player. 
- Its modified by `add_quest_string()` and `remove_quest_string()` which are adding / removing new entries 
- added signal to notify UI for quest-updates 
- modified `add_npc_talked_to` to accommodate adding / removing a quest upon interaction
- added new method to visualize quest in `overworldui` ( similar to the previous methods, primarily as dummy until UI was added ) 
Ran it in the overworld with its default npcs: 
before submitting "Evillyn"s quest ( talking to esther) …
> overworld | add methods to add/remove quests, add them to ui for tracking purpose

- Arch-enemies/bridges/script/grid.gd
closes #219 
closes #231 (at least I think it should fix it)
When changing a tile in update grid it now correctly checks the hierarchy using tile_update.
https://github.com/mango-gremlin/arch-enemies/assets/65815628/508177e6-f6f7-4ba4-aef5-ca4651784be0
> bridges | implement hierarchy for tiles

- Arch-enemies/bridges/script/grid_drag.gd
closes #214
When dragging the cursor to the edge it could crash the game because wrong array elements might be accessed.
An out_of_bounds function was added that checks if the current cursor position would check an illegal square for the current
animal. This is based on the animals sprite size (which is very handy to implement for other animals).
https://github.com/mango-gremlin/arch-enemies/assets/65815628/c3b5a870-7528-42f1-a6ad-6a26e4834f1b
> bridges | Fixed boundary issues

- Arch-enemies/bridges/scenes/Grid.tscn
- Arch-enemies/bridges/script/Camera.gd
- Arch-enemies/bridges/script/grid.gd
closes #248
To implement additional levels it would be good if the grid adjusts automatically so we can just repeatedly implement the same scene.
Camera has it's own script now. It just sends it current zoom. Since camera is often used for many things giving it it's own script is future proofing. On ready the grid.gd now signals to get the zoom and with that adjusts the grid size.
The grid looks the same even though the sizes are not hard coded.
Note that if you adjust the zoom you have to adjust the camera position, but this is trivially true.
> bridges | Added the dynamic grid

- Arch-enemies/bridges/scenes/Grid.tscn
- Arch-enemies/bridges/script/grid.gd
closes #174 
The pause_menu wasn't accessible in the new bridge level, so it needed to be added.
The pause_menu isn't accessed by changing the scene like before, but by having a pause_menu node inside of the scene.
Opening it by pressing "esc" just changes the visibility of the node, so it can be opened and closed.
https://github.com/mango-gremlin/arch-enemies/assets/116217918/7ab09900-117f-4232-b3f7-9ba650c068e3
You can open and close the pause_menu by pressing "esc". 
Interestingly enough it looks different when it actually changes the scene like in the overworld eventhough it's the same menu.
You can still move the animals when the pause_menu is pressed. This is also the case in the goal_menu, so if we want to change this, both should be edited.
Both of the menus should also be updated …
> bridges | added pause menu to new bridge level

- Arch-enemies/overworld/scripts/save_management.gd
merging the bridge inventory and also updating the save management --> while also setting it with default values 
the **debugging function to set an arbitrary animal-inventory** was overwritten by the save management that loads a state upon instantiation. 
This is now fixed, by removing the empty inventory from the save management. 
Furher I added a flag that indicates where to set the inventory once it can be saved / loaded accordingly.
Tested by @aylinfi  live
> overworld | bridge remove empty inventory to overwrite state saved in singleton

- Arch-enemies/bridges/script/grid_drag.gd
closes #263
Updated the logic for squirrel, so it accounts for SHALLOW, which means setting the `is_free` to false when any part of the squirrel would end up in shallows. 
As you can see, the illegal placement as described in #263 is no longer possible.
https://github.com/mango-gremlin/arch-enemies/assets/104799849/3f726aed-3f50-44e1-9228-381725aa9a5e
As you can see, the squirrel still should work elsewhere
https://github.com/mango-gremlin/arch-enemies/assets/104799849/416c3cc2-439d-4c9f-a75a-8bebd9e68dd0
> Extended squirrel logic for shallow

- Arch-enemies/bridges/script/grid_drag.gd
closes #264
Because we start dragging an animal before checking the inventory, the helping grid appears even though you might not be able to drag the animal.
Move the inventory check at the top of get_drag_data.
https://github.com/mango-gremlin/arch-enemies/assets/57258671/252e4ddd-e2e3-4a5a-9fa4-e6f95ded00ac
Works with the test inventory.
> bridges | check inventory before dragging

- Arch-enemies/bridges/scenes/Grid.tscn
- Arch-enemies/bridges/script/goal_menu.gd
- Arch-enemies/bridges/script/grid.gd
- Arch-enemies/bridges/script/grid_drag.gd
- Arch-enemies/overworld/entities/Player/Player.gd
- Arch-enemies/singleton_scripts/singleton_player.gd
closes #250
After the level is finished (which happens when entering the _goal area_), we want to update the global inventory and bridge connection list.
When clicking the "Continue" button in the goal menu, the SingletonPlayer inventory is updated and the necessary bridge-edges are added.
Because while returning to the overworld we will not change the level, nothing else has to be changed.
https://github.com/mango-gremlin/arch-enemies/assets/57258671/d793841a-b36c-4e44-8de9-7f631c33e4b4
Through print statements before and after you can see that the bridge edge was added correctly.
For this implementation to work the current level must exist in SingletonPlayer.bridge_level_scenes. If there is a better solution to find out which BridgeEdge we are using in the current level, let me know.
> bridges | update singleton after level was solved

- Arch-enemies/bridges/script/grid.gd
- Arch-enemies/singleton_scripts/singleton_player.gd
I observed a bug that updates the wrong inventory upon entering the overworld after a level was solved. 
I have not seen it when reviewing the PR, my bad / sorry. 
Additionally I gave some _more reasonable_ values for the test inventory --> so that ones does not have to change it that often. This will likely collide with #278 
using the right method in "grid.gd" to update the animal_inventory instead of item_inventory.
Well, solve the level and you should observe that the updated inventory should be displayed in the "ui".
> Bug | leaving overworld updates item inventory instead of animal inventory 

- Arch-enemies/bridges/scenes/0_TutorialLevel.tscn
- Arch-enemies/bridges/scenes/1_FrogHazardLevel.tscn
- Arch-enemies/bridges/scenes/2_FinalLevel.tscn
- Arch-enemies/bridges/scenes/bridges_pause_menu.tscn
- Arch-enemies/bridges/scenes/goal_menu.tscn
closes #288
Updated menu design to adjust to different level sizes.
The pause and goal menu was extended to the sides to adjust for bigger grid sizes. Extensions up and down can be provided via scaling the pause menu when needed.
Everything was centred to origin to make things easier to place.
The new goal menu (pause menu is changed the same way):
https://github.com/mango-gremlin/arch-enemies/assets/57258671/652d0f51-945b-4065-aa9d-f272be902055
It still works for the bigger levels.
As seen in the video, everything is kinda squished for the frog hazard level because the zoom is not the same for the x and y axis. It should be considered to change that, or find another way.
> bridges | update menus for the new levels

- Arch-enemies/overworld/entities/Player/Player.gd
- Arch-enemies/overworld/entities/interaction_overworld/interactionspot.gd
- Arch-enemies/overworld/entities/interaction_overworld/item_interaction.gd
- Arch-enemies/overworld/entities/interaction_overworld/item_interaction.tscn
- Arch-enemies/overworld/main_scene_overworld.tscn
- Arch-enemies/overworld/overworld_test_area.tscn
- Arch-enemies/overworld/scenes/world.tscn
- Arch-enemies/singleton_scripts/singleton_player.gd
resolves #179 
- also uses this addition to add _state management_ to maintain item amounts after scene changes occurred
- resolves **visibility** of item once its resource was depleted. 
- removes debug message when interacting with an item
-  removes unused variables from item_interaction
- updated `item_interaction`, removed unused variables
- added dictionary to track items and their known amount -> representation as dictionary ( key:itemspotID,value:QuantityAvailable) 
- now binding specific node references \@onready 
- update_visibility sets visibility of sprite denoting an interaction
1. open overworld 
2. obtain an item -> should be invisible now!
3. open pause menu and return --> itemspot state prevails 
4. enter bridge scene 
5. return to overworld --> itemspot state prevails
> overworld | hide item when it was taking | add states to save progress after scene change

- Arch-enemies/overworld/dialogue/Dialogue.gd
- Arch-enemies/overworld/dialogue/DialogueUI.gd
- Arch-enemies/overworld/dialogue/DialogueUI.tscn
- Arch-enemies/overworld/dialogue/Dialogue_Data.gd
- Arch-enemies/overworld/dialogues/QuestTrackingNPC/QuestTrackingNPC.gd
- Arch-enemies/overworld/dialogues/test_dialogue/Page-Quest-Done1.gd
- Arch-enemies/overworld/dialogues/test_dialogue/Page1.gd
- Arch-enemies/overworld/dialogues/test_dialogue/Page2.gd
- Arch-enemies/overworld/dialogues/test_dialogue/Page3.gd
- Arch-enemies/overworld/entities/interaction_overworld/npc_interaction.gd
- Arch-enemies/singleton_scripts/singleton_player.gd
Adds name of the given npc to every dialogue box they have.
Does not resolve a specific issue ( was discussed internally )
Also went over the implementation of the Dialogue-System and added / rewrote some minor portions to improve readability. 
**Warning**:
With this change names are set the following: 
1. each Dialogue contains a variable "npc_name" which denotes the name to display. Its "" at first, so empty
2. To update this dynamically we have to set this name whenever the npcs linked to the dialogue are initialized ( before that we cannot obtain their name cus its contained in their construction / object, which is only available after they've been loaded at least once ) 
3. then the name is statically taken from the internal variable set in `Dialogue_Data`
- renamed few things in …
> Overworld | add Npc name to dialogue 

- Arch-enemies/bridges/scenes/player.tscn
closes #313 
I increased the maximum slope angle of the bridge player to 50 Degrees
https://github.com/mango-gremlin/arch-enemies/assets/59502349/f459fc38-e1f4-4076-86e5-ec6112910d8a
> increased max slope of bridge player to 50

- Arch-enemies/overworld/dialogue/Dialogue.gd
- Arch-enemies/overworld/dialogue/Dialogue_Data.gd
- Arch-enemies/overworld/dialogues/DynamicDialogue/DynamicDialogue.gd
- Arch-enemies/overworld/dialogues/QuestTrackingNPC/QuestTrackingNPC.gd
- Arch-enemies/singleton_scripts/singleton_player.gd
resolves #308  
fixes **deer** not showing their quest-done dialogue after all quest were done 
simplifies inserting done/undone quest pages into deer NPC
**does not resolve**:
- ~~questTracker : always show first page ( that it did not join the group yet ) --> will be done before closing this~~ done 
I've changed how the **active** set of pages is selected by adding `var active_pages:Array[Dialogue_Entry] = []` in Dialogue_Data. It denotes which set of pages is actively displayed when **entering a dialogue**
**It defaults** to the _undone-quest_. 
--> once the quest was done it will then be **updated** to the quest_done pages and those will be displayed.
This allows to **remove** `select_quest_done` as it mimics `select_page()`.
**Creating a new Dialogue**:
to create a new dialogue we …
> overworld | improve deer npc, handling undone / done quest dialogues 

- Arch-enemies/overworld/entities/Player/Player.gd
It was requested that replaying a solved level should be allowed. 
removed check whether it was solved already 
-> allowing to enter a bridge-level that was done before.
> overworld | allow replaying bridge level after it was done

- Arch-enemies/bridges/scenes/dragpreview.tscn
- Arch-enemies/bridges/script/DRAGPREVIEW.gd
- Arch-enemies/bridges/script/grid.gd
- Arch-enemies/bridges/script/grid_drag.gd
closes #315
The placement of animals was based on the cursor at the lower left corner and not the dragpreview which was confusing for players.
It is nicer to have the cursor in the center of the dragpreview.
The problem with centering the cursor on the dragpreview was that `_can_drop_data()` wasn't called anymore and nothing could be placed. This was due to the preview being a different scene, not connected to our `_can_drop_data()` function.
This could be solved by adding it and also the `_drop_data()` function to `DRAGPREVIEW.gd` which is connected to the dragpreview.tscn scene. These new functions just call the old functions in `grid_drag.gd`(this is not the greatest coding but it works).
Other than that the new positions of deer and snake needed to be adjusted, because we were using …
> center the dragpreview of the animals

- Arch-enemies/overworld/ui/main_menu/main_menu.tscn
closes #325 
While it did work in the editor, in the export version the main menu buttons were misaligned.
Delete one whitespace. 
I'm 99.9% sure it will work, but until someone shows me how to export this game, I can't test it.
> Fix main menu export

- Arch-enemies/overworld/dialogues/OverworldDialogues.gd
closes #336 
Snake talks about being able to swim which confused some playtesters, because it is not a game mechanic.
I deleted the snake talking about being able to swim
No more swimming snakes.
> Quick deletion of snake swimming dialog

- Arch-enemies/overworld/dialogue/Dialogue.gd
- Arch-enemies/overworld/dialogue/Dialogue_Data.gd
- Arch-enemies/overworld/dialogues/OverworldDialogues.gd
- Arch-enemies/singleton_scripts/singleton_player.gd
Something went wrong with the branch and I (Kabooni) couldn't commit to it. Here's a new updated pr.
resolves #329 
added variable to dialogue_data that tracks whether we spoke to the npc before.
Upon solving their quest before speaking to them the dialogue will be entered again ( and display the solved one ). 
It will then set this variable  to true preventing this to loop forever. 
This adds an invariant. 
Also added new dialogue to inform the player that an item was given to the npc.
Well test the following: 
1. gather nut and fly
2. speak to squirrel and observe behavior 
3. speak to spider and observe behavior 
4. speak to snake afterwards
The quest solved dialogue now contains an action dialogue for giving an item. E.g. for the spider:
> overworld | improve quest dialogues

- Arch-enemies/bridges/scenes/goal_menu.tscn
- Arch-enemies/bridges/script/goal_menu.gd
closes #359 
Added a back button to the goal menu which implements the behavior described in the issue.
https://github.com/mango-gremlin/arch-enemies/assets/59502349/6a1bf56c-4e8a-428e-ada5-d566b80a020f
> bridges | implemented/added back button in goal menu

- Arch-enemies/overworld/dialogue/Dialogue.gd
resolves a bug that was added after merging #352 :
Specifically one could talk to a npc, get their requirement and submit the quest. Once that was done the dialogue for solving the quest was shown twice - because the internal tracking of "spoken_to_before" was not updated on each occasion. 
To resolve the internal state is now updated upon exiting the dialogue - every time. 
As in #352 you can try the following:
**solve quest without prior talk**: 
1. gather item for one npc 
2. talk to npc and observe whether the quest done dialogue is shown after the initial dialogue
**solve quest with prior talking**: 
1. talk to npc 
2. gather their requirement 
3. talk to them again and observe the quest_done_dialogue to show up only once! 
---
> overworld | dialogue playing twice if quest solved

- Arch-enemies/bridges/scenes/0_TutorialLevel.tscn
- Arch-enemies/bridges/scenes/player.tscn
- Arch-enemies/bridges/script/player.gd
closes #328
It would be nice to give the player a small grace period before falling, where jumping is still allowed.
Added a timer, which starts when falling and allows jumping once for a duration of `coyote_frames / 60`. I set the frame number to 8 but this can be changed easily in the editor.
https://github.com/mango-gremlin/arch-enemies/assets/57258671/691ccdc9-af24-4cfd-83e3-2b8bf552f8c8
> bridges | add coyote timer for jumping

- Arch-enemies/overworld/entities/interaction_overworld/npc_interaction.gd
- Arch-enemies/overworld/entities/interaction_overworld/npc_interaction.tscn
- Arch-enemies/overworld/scenes/world.tscn
closes #365 
NPCs had no collision as of the first playtest.
Added a collision shape (circle), depending on the npc sprite, the position and size of it is changed to approximate the sprite.
Also added collision to the frogs on the frog island (these are just the frog hazard tile)
https://github.com/mango-gremlin/arch-enemies/assets/104830903/0a295b68-9451-4411-aaac-d06136e501bd
> overworld | collision size and pos of npc interaction determined from sprite
